name: Update PR in front-web-platform

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  automatic-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      BASE_BRANCH: master
      PR_BRANCH: update-translations
      REPOSITORY: front-web-platform
      REPOSITORY_FULL: FrontFin/front-web-platform
    steps:
      - uses: actions/create-github-app-token@v2
        id: app
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          repositories: ${{ env.REPOSITORY }}

      - uses: actions/checkout@v4
        id: checkout
        with:
          repository: ${{ env.REPOSITORY_FULL }}
          token: ${{ steps.app.outputs.token }}
          submodules: true
          ref: ${{ env.BASE_BRANCH }}

      - name: Setup git config
        uses: qoomon/actions--setup-git@v1
        with:
          user: GitHub Actions <noreply@github.com>

      - name: Get latest version of translations
        run: |
          cd ./packages/localization/locales
          git checkout main
          cd ../../../
          git add .

      - name: Create pull request
        id: create-pr
        continue-on-error: true
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.app.outputs.token }}
          branch: '${{ env.PR_BRANCH }}'
          base: ${{ env.BASE_BRANCH }}
          title: 'Automatic PR: Update translations'
          body: >
            This automatically created Pull Request includes the latest changes for the translations.
          team-reviewers: 'FrontFin/frontend'
          commit-message: 'Update translations'
